- name: disabling the nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enabling nodejs
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: installing nodejs and mysql
  dnf:
    name:
    - nodejs
    - mysql
    state: present

- name: install python mysql dependencies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9 # pip3.11 if python version is 3.11

- name: adding the user
  ansible.builtin.user:
    name: expense

- name: run app-pre-req
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: download the dependencies
  ansible.builtin.command: npm install 
  args:
    chdir: /app

- name: copying the servie file 
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: import data into mysql
  community.mysql.mysql_db:
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    state: import
    name: all 
    target: /app/schema/backend.sql

- name: reloading the backend
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable backend service
  ansible.builtin.service:
    name: backend
    state: started
    enabled: yes