- name: Installing the Mysql-Server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Enabling and starting the server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes 

- name: install python mysql dependencies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9 # pip3.11 if python version is 3.11

- name: Check the DB connection
  community.mysql.mysql_info:
    login_host: "{{ db_host }}"
    login_user: "{{ db_user  }}"
    login_password: "{{ db_password }}" 
  ignore_errors: yes
  register: mysql_output

- name: print output
  ansible.builtin.debug:
    msg: "output is {{ mysql_output }}"  

- name: Setting up the root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ db_password }}
  when: mysql_output.failed is true 