- name: nginx
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started    
  - name: removing default contents
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent
  - name: creating the directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory
  -  name: get the frontend code
     ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  - name: unzip the frontendcode
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  - name: copying the servie file 
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf
  - name: restart nginx 
    ansible.builtin.service:
      name: nginx
      state: restarted 
  