- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: latest

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started 
    enabled: true

- name: run app-pre-req
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req 

- name: copying the servie file 
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf 
  notify:
  - restart nginx

# - name: restart nginx 
#   ansible.builtin.service:
#     name: nginx
#     state: restarted 
